2023-12-29 16:09:27,736 - root - INFO - Table asset already exists.
2023-12-29 16:09:27,738 - root - INFO - Table bond_yield already exists.
2023-12-29 16:09:27,740 - root - INFO - Table bond_yield_realtime already exists.
2023-12-29 16:31:25,031 - root - INFO - Table asset already exists.
2023-12-29 16:31:25,033 - root - INFO - Table bond_yield already exists.
2023-12-29 16:31:25,035 - root - INFO - Table bond_yield_realtime already exists.
2023-12-29 16:52:35,256 - root - INFO - Table asset already exists.
2023-12-29 16:52:35,260 - root - INFO - Table bond_yield already exists.
2023-12-29 16:52:35,262 - root - INFO - Table bond_yield_realtime already exists.
2023-12-29 16:54:48,835 - root - INFO - Table asset already exists.
2023-12-29 16:54:48,845 - root - INFO - Table bond_yield already exists.
2023-12-29 16:54:48,849 - root - INFO - Table bond_yield_realtime already exists.
2023-12-30 00:55:37,522 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f41d05b3c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/fc65ca34-753c-4f97-a730-cb6a311c784b
2023-12-30 00:55:37,524 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4206e99b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/fc65ca34-753c-4f97-a730-cb6a311c784b
2023-12-30 00:55:37,525 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f41d058c0b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/fc65ca34-753c-4f97-a730-cb6a311c784b
2023-12-30 00:55:37,551 - logger_realtime_data - INFO - 2023-12-30 00:55:00+08:00
2023-12-30 00:55:37,554 - logger_realtime_data - INFO - 2023-12-30 00:55:37.544569+08:00
2023-12-30 00:56:21,641 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f251b853bc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6b870160-f668-4086-ae81-a4f7e075271d
2023-12-30 00:56:21,642 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f251e3c4c20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6b870160-f668-4086-ae81-a4f7e075271d
2023-12-30 00:56:21,643 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f251b853fb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6b870160-f668-4086-ae81-a4f7e075271d
2023-12-30 00:56:21,671 - logger_realtime_data - INFO - 2023-12-30 00:56:00+08:00
2023-12-30 00:56:21,673 - logger_realtime_data - INFO - 2023-12-30 00:56:21.667542+08:00
2023-12-29 16:56:52,450 - root - INFO - Table asset already exists.
2023-12-29 16:56:52,454 - root - INFO - Table bond_yield already exists.
2023-12-29 16:56:52,455 - root - INFO - Table bond_yield_realtime already exists.
2023-12-30 00:57:32,940 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9313357320>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ff3fb3d4-dec4-495a-a967-3bb2cda8a5e2
2023-12-30 00:57:32,941 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9313357080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ff3fb3d4-dec4-495a-a967-3bb2cda8a5e2
2023-12-30 00:57:32,941 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9313357d40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ff3fb3d4-dec4-495a-a967-3bb2cda8a5e2
2023-12-30 00:57:32,986 - logger_realtime_data - INFO - 2023-12-30 00:57:00+08:00
2023-12-30 00:57:32,988 - logger_realtime_data - INFO - 2023-12-30 00:57:32.968529+08:00
2023-12-30 00:58:25,103 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b20acc170>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/90331c1c-d862-4e90-8b5b-dd914d0f3f24
2023-12-30 00:58:25,105 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b20acc080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/90331c1c-d862-4e90-8b5b-dd914d0f3f24
2023-12-30 00:58:25,107 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b20acc320>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/90331c1c-d862-4e90-8b5b-dd914d0f3f24
2023-12-30 00:58:25,135 - logger_realtime_data - INFO - 2023-12-30 00:58:00+08:00
2023-12-30 00:58:25,136 - logger_realtime_data - INFO - 2023-12-30 00:58:25.125472+08:00
2023-12-30 00:59:19,747 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf5af9340>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bbe2b146-5b0b-4be5-8c75-9707971260bf
2023-12-30 00:59:19,748 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf89cddf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bbe2b146-5b0b-4be5-8c75-9707971260bf
2023-12-30 00:59:19,749 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf5ad0110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bbe2b146-5b0b-4be5-8c75-9707971260bf
2023-12-30 00:59:19,767 - logger_realtime_data - INFO - 2023-12-30 00:59:00+08:00
2023-12-30 00:59:19,769 - logger_realtime_data - INFO - 2023-12-30 00:59:19.762811+08:00
2023-12-30 01:00:13,471 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ad57492b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b050953c-158a-4d48-9084-a00d82714053
2023-12-30 01:00:13,472 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ad82c5700>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b050953c-158a-4d48-9084-a00d82714053
2023-12-30 01:00:13,473 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ad574b860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b050953c-158a-4d48-9084-a00d82714053
2023-12-30 01:00:13,494 - logger_realtime_data - INFO - 2023-12-30 01:00:00+08:00
2023-12-30 01:00:13,495 - logger_realtime_data - INFO - 2023-12-30 01:00:13.489164+08:00
2023-12-30 01:01:17,119 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcda9d6af90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8612f67a-3aca-4eb0-87d2-4e6d2f29a4da
2023-12-30 01:01:17,120 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdaa414e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8612f67a-3aca-4eb0-87d2-4e6d2f29a4da
2023-12-30 01:01:17,121 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcda9d6c0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8612f67a-3aca-4eb0-87d2-4e6d2f29a4da
2023-12-30 01:01:17,140 - logger_realtime_data - INFO - 2023-12-30 01:01:00+08:00
2023-12-30 01:01:17,141 - logger_realtime_data - INFO - 2023-12-30 01:01:17.137505+08:00
2023-12-30 01:02:18,886 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8f3093dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/eeb655d4-a760-49f3-a03a-9de24835f6f0
2023-12-30 01:02:18,887 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8f41d8650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/eeb655d4-a760-49f3-a03a-9de24835f6f0
2023-12-30 01:02:18,888 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8f306c140>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/eeb655d4-a760-49f3-a03a-9de24835f6f0
2023-12-30 01:02:18,909 - logger_realtime_data - INFO - 2023-12-30 01:02:00+08:00
2023-12-30 01:02:18,910 - logger_realtime_data - INFO - 2023-12-30 01:02:18.902885+08:00
2023-12-30 01:03:14,698 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f56ad422780>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a5adc87c-33d9-4fcd-8c7d-0a603bb912dc
2023-12-30 01:03:14,701 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f56af874290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a5adc87c-33d9-4fcd-8c7d-0a603bb912dc
2023-12-30 01:03:14,702 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f56ad4241a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a5adc87c-33d9-4fcd-8c7d-0a603bb912dc
2023-12-30 01:03:14,734 - logger_realtime_data - INFO - 2023-12-30 01:03:00+08:00
2023-12-30 01:03:14,739 - logger_realtime_data - INFO - 2023-12-30 01:03:14.716028+08:00
2023-12-30 01:04:28,442 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0698e6de0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a70781b6-f2af-4ff6-a69d-96017121b1e4
2023-12-30 01:04:28,443 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0698e7c20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a70781b6-f2af-4ff6-a69d-96017121b1e4
2023-12-30 01:04:28,444 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0698c0050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a70781b6-f2af-4ff6-a69d-96017121b1e4
2023-12-30 01:04:28,475 - logger_realtime_data - INFO - 2023-12-30 01:04:00+08:00
2023-12-30 01:04:28,477 - logger_realtime_data - INFO - 2023-12-30 01:04:28.468698+08:00
2023-12-30 01:05:21,760 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5330353800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8a73e8c3-55eb-4020-970c-4f4f3926842a
2023-12-30 01:05:21,762 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5330352f60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8a73e8c3-55eb-4020-970c-4f4f3926842a
2023-12-30 01:05:21,763 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5330328110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8a73e8c3-55eb-4020-970c-4f4f3926842a
2023-12-30 01:05:21,790 - logger_realtime_data - INFO - 2023-12-30 01:05:00+08:00
2023-12-30 01:05:21,793 - logger_realtime_data - INFO - 2023-12-30 01:05:21.781916+08:00
2023-12-30 01:06:14,515 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf1809e810>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/01fdd2ff-9533-40a6-8e7b-492ce81fbdbc
2023-12-30 01:06:14,517 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf1910f2f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/01fdd2ff-9533-40a6-8e7b-492ce81fbdbc
2023-12-30 01:06:14,520 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf1809fdd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/01fdd2ff-9533-40a6-8e7b-492ce81fbdbc
2023-12-30 01:06:14,539 - logger_realtime_data - INFO - 2023-12-30 01:06:00+08:00
2023-12-30 01:06:14,540 - logger_realtime_data - INFO - 2023-12-30 01:06:14.535211+08:00
2023-12-30 01:07:17,991 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f695751c0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/884460dd-42b5-4216-a134-e277281440d1
2023-12-30 01:07:17,993 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f695a0bae10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/884460dd-42b5-4216-a134-e277281440d1
2023-12-30 01:07:17,994 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f695751c380>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/884460dd-42b5-4216-a134-e277281440d1
2023-12-30 01:07:18,019 - logger_realtime_data - INFO - 2023-12-30 01:07:00+08:00
2023-12-30 01:07:18,020 - logger_realtime_data - INFO - 2023-12-30 01:07:18.015168+08:00
2023-12-30 01:08:17,718 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb93f35f500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/37aa7660-4315-49d8-a771-0de8b7b3fed9
2023-12-30 01:08:17,720 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb94184eed0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/37aa7660-4315-49d8-a771-0de8b7b3fed9
2023-12-30 01:08:17,720 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb93f35ffe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/37aa7660-4315-49d8-a771-0de8b7b3fed9
2023-12-30 01:08:17,740 - logger_realtime_data - INFO - 2023-12-30 01:08:00+08:00
2023-12-30 01:08:17,741 - logger_realtime_data - INFO - 2023-12-30 01:08:17.736842+08:00
2023-12-30 01:09:16,080 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d38d15a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ca40c762-01f0-4ac5-a4e8-0556c85b4871
2023-12-30 01:09:16,082 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d3b8a9010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ca40c762-01f0-4ac5-a4e8-0556c85b4871
2023-12-30 01:09:16,083 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d38d18080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ca40c762-01f0-4ac5-a4e8-0556c85b4871
2023-12-30 01:09:16,105 - logger_realtime_data - INFO - 2023-12-30 01:09:00+08:00
2023-12-30 01:09:16,107 - logger_realtime_data - INFO - 2023-12-30 01:09:16.096751+08:00
2023-12-30 01:10:15,253 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cbeb57620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ab612e8e-951a-4b26-a012-3ef0f6aac93a
2023-12-30 01:10:15,254 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cbf54ecc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ab612e8e-951a-4b26-a012-3ef0f6aac93a
2023-12-30 01:10:15,255 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cbeb30080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ab612e8e-951a-4b26-a012-3ef0f6aac93a
2023-12-30 01:10:15,272 - logger_realtime_data - INFO - 2023-12-30 01:10:00+08:00
2023-12-30 01:10:15,274 - logger_realtime_data - INFO - 2023-12-30 01:10:15.269416+08:00
2023-12-30 01:11:19,516 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0268f76d80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d6d09ac5-23fc-4c01-b1e7-a0665bfc0914
2023-12-30 01:11:19,516 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f026adbc650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d6d09ac5-23fc-4c01-b1e7-a0665bfc0914
2023-12-30 01:11:19,517 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0268f500b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d6d09ac5-23fc-4c01-b1e7-a0665bfc0914
2023-12-30 01:11:19,535 - logger_realtime_data - INFO - 2023-12-30 01:11:00+08:00
2023-12-30 01:11:19,536 - logger_realtime_data - INFO - 2023-12-30 01:11:19.531675+08:00
2023-12-29 17:11:58,221 - root - INFO - Table asset already exists.
2023-12-29 17:11:58,223 - root - INFO - Table bond_yield already exists.
2023-12-29 17:11:58,225 - root - INFO - Table bond_yield_realtime already exists.
