Server TLS handshake failed. connection closed
Server TLS handshake failed. connection closed
Server TLS handshake failed. connection closed
Server TLS handshake failed. connection closed
Server TLS handshake failed. connection closed
Server TLS handshake failed. connection closed
Exception ignored in: <function StreamWriter.__del__ at 0x7f8ce250df80>
Traceback (most recent call last):
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 397, in __del__
    self.close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 1206, in close
    super().close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 871, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 772, in call_soon
    self._check_closed()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7f8ce250df80>
Traceback (most recent call last):
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 397, in __del__
    self.close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 1206, in close
    super().close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 871, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 772, in call_soon
    self._check_closed()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7f8ce250df80>
Traceback (most recent call last):
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 397, in __del__
    self.close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 1206, in close
    super().close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 871, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 772, in call_soon
    self._check_closed()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7f8ce250df80>
Traceback (most recent call last):
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 397, in __del__
    self.close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 1206, in close
    super().close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 871, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 772, in call_soon
    self._check_closed()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function StreamWriter.__del__ at 0x7f8ce250df80>
Traceback (most recent call last):
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 397, in __del__
    self.close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 1206, in close
    super().close()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/selector_events.py", line 871, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 772, in call_soon
    self._check_closed()
  File "/opt/conda/envs/bonds/lib/python3.12/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
